# Generated by Django 2.2.4 on 2020-12-14 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_validations', '0003_taskmanager'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TaskManager',
        ),
    ]
